version: '2.3'

services:
  web:
    build: ./server
    command: ./entrypoint.sh
    network_mode: "host"
    env_file:
        - ./server/webserver/.env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=TTsrFc4(#aGuj
      - POSTGRES_DB=speedcraft
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 6
